openapi: 3.0.0
info:
  title: Okta
  description: okta
  version: "1.0"
  x-logo: ""
  contact:
    name: "@frikkylikeme"
    url: https://twitter.com/frikkylikeme
    email: frikky@shuffler.io
  x-categories:
    - IAM
servers:
  - url: ""
basePath: /
schemes:
  - ""
paths:
  /api/v1/users:
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: >
                  {
                    "id": "00ub0oNGTSWTBKOLGLNR",
                    "status": "STAGED",
                    "created": "2013-07-02T21:36:25.344Z",
                    "activated": null,
                    "statusChanged": null,
                    "lastLogin": null,
                    "lastUpdated": "2013-07-02T21:36:25.344Z",
                    "passwordChanged": null,
                    "profile": {
                      "firstName": "Isaac",
                      "lastName": "Brock",
                      "email": "isaac.brock@example.com",
                      "login": "isaac.brock@example.com",
                      "mobilePhone": "555-415-1337"
                    },
                    "credentials": {
                      "provider": {
                        "type": "OKTA",
                        "name": "OKTA"
                      }
                    },
                    "_links": {
                      "activate": {
                        "href": "https://${yourOktaDomain}/api/v1/users/00ub0oNGTSWTBKOLGLNR/lifecycle/activate"
                      },
                      "self": {
                        "href": "https://${yourOktaDomain}/api/v1/users/00ub0oNGTSWTBKOLGLNR"
                      }
                    }
                  }
      summary: Create User without Credentials
      operationId: Create_User_without_Credentials
      description: Creates a user without a password or recovery question & answer
      parameters:
        - in: query
          name: activate
          description: Generated by shuffler.io OpenAPI
          required: true
          schema:
            type: string
          example: "false"
        - in: body
          name: body
          multiline: true
          description: Generated by shuffler.io OpenAPI
          required: false
          example: |-
            "profile": {
                "firstName": "${firstname}",
                "lastName": "${lastname}",
                "email": "${email}",
                "login": "${login}",
                "mobilePhone": "${mobile_phone}"
              }
          schema:
            type: string
        - in: header
          name: '"Accept'
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: 'application/json" '
          schema:
            type: string
        - in: header
          name: '"Content-Type'
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: 'application/json" '
          schema:
            type: string
      requestBody:
        description: Generated by Shuffler.io
        required: false
        content:
          example:
            example: |-
              "profile": {
                  "firstName": "${firstname}",
                  "lastName": "${lastname}",
                  "email": "${email}",
                  "login": "${login}",
                  "mobilePhone": "${mobile_phone}"
                }
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
    SSWS:
      type: apiKey
      in: header
      name: SSWS
